AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Yoja Webhook

Parameters:
  OauthClientId:
    Type: String
  OauthClientSecret:
    Type: String
  DropboxOauthClientId:
    Type: String
  DropboxOauthClientSecret:
    Type: String
  UsersTable:
    Type: String
  ServiceconfTable:
    Type: String
  YojaApiEntrypointFunctionArn:
    Type: String
Globals:
  Function:
    Environment:
      Variables:
        OAUTH_CLIENT_ID: !Ref OauthClientId
        OAUTH_CLIENT_SECRET: !Ref OauthClientSecret
        DROPBOX_OAUTH_CLIENT_ID: !Ref DropboxOauthClientId
        DROPBOX_OAUTH_CLIENT_SECRET: !Ref DropboxOauthClientSecret
        USERS_TABLE: !Ref UsersTable
        SERVICECONF_TABLE: !Ref ServiceconfTable
        PYTHONUNBUFFERED: 'True'
        YOJA_LAMBDA_ARN: !Ref YojaApiEntrypointFunctionArn
Metadata:
  AWS::ServerlessRepo::Application:
    Name: YojaWebhookApi
    Description: Yoja Webhook API
    Author: Yoja AI
    SpdxLicenseId: MIT
    LicenseUrl: ../../LICENSE
    # ReadmeUrl: README.md
    Labels: ['tests']
    HomePageUrl: https://www.yoja.ai
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/yoja-ai/yoja
Resources:
  YojaWebhookLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        -
          PolicyName: 'AllowSTS'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                Resource: '*'
        -
          PolicyName: 'AllowPassRole'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - 'execute-api:Invoke'
                Resource: '*'
        -
          PolicyName: 'AllowInvokeOtherLambda'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: '*'
        -
          PolicyName: AllowDdb
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:PutItem
              - dynamodb:DescribeTable
              - dynamodb:DeleteItem
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem
              Resource:
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/yoja-users
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/yoja-users/index/dropbox_sub-index
              - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/yoja-ServiceConf
  YojaWebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,HEAD,OPTIONS,POST,PUT,PATCH,DELETE'"
        AllowHeaders: "'Access-Control-Allow-Headers,Access-Control-Allow-Origin,Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,x-requested-with,X-Api-Key,Authorization,X-Amz-Date,X-Forwarded-For,Idtoken'"
        AllowCredentials: false
  LayerVersion:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: yoja-webhook-layer
      Description: Dependencies for the yoja webhook APIs
      ContentUri: layer-build/.
      CompatibleRuntimes:
        - python3.11
  webhookgdrive:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Layers:
        - !Ref LayerVersion
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Runtime: python3.11
      Handler: webhook_gdrive.webhook_gdrive
      Description: Yoja Webhook for Gdrive
      Role: !GetAtt YojaWebhookLambdaRole.Arn
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
        Cors:
          AllowCredentials: true
          AllowHeaders:
            - authorization
          AllowMethods:
            - '*'
          AllowOrigins:
            - '*'
          ExposeHeaders:
            - access-control-allow-origin
            - access-control-allow-headers
            - access-control-allow-methods
            - access-control-allow-credentials
          MaxAge: 30
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref YojaWebhookApi
            Path: /webhook_gdrive
            Method: ANY
  webhookdropbox:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Layers:
        - !Ref LayerVersion
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Runtime: python3.11
      Handler: webhook_dropbox.webhook_dropbox
      Description: Yoja Webhook for Dropbox
      Role: !GetAtt YojaWebhookLambdaRole.Arn
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
        Cors:
          AllowCredentials: true
          AllowHeaders:
            - authorization
          AllowMethods:
            - '*'
          AllowOrigins:
            - '*'
          ExposeHeaders:
            - access-control-allow-origin
            - access-control-allow-headers
            - access-control-allow-methods
            - access-control-allow-credentials
          MaxAge: 30
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref YojaWebhookApi
            Path: /webhook_dropbox
            Method: ANY
Outputs:
  GDriveWebhookFunctionArn:
    Description: The Arn of the GDrive webhook lambda
    Value: !GetAtt webhookgdrive.Arn
    Export:
      Name: 'yoja:GDriveWebhookFunctionArn'
  DropboxWebhookFunctionArn:
    Description: The Arn of the Dropbox webhook lambda
    Value: !GetAtt webhookdropbox.Arn
    Export:
      Name: 'yoja:DropboxWebhookFunctionArn'
  GDriveWebhookFunctionUrlConfig:
    Description: The FunctionUrlConfig of the GDrive webhook lambda
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-functionurlconfig.html
    # https://xxxx.lambda-url.us-east-1.on.aws/
    Value: !GetAtt webhookgdriveUrl.FunctionUrl
    Export:
      Name: 'yoja:GDriveWebhookFunctionUrlConfig' 
  DropboxWebhookFunctionUrlConfig:
    Description: The FunctionUrlConfig of the dropbox webhook lambda
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-functionurlconfig.html
    # https://xxxx.lambda-url.us-east-1.on.aws/
    Value: !GetAtt webhookdropboxUrl.FunctionUrl
    Export:
      Name: 'yoja:DropboxWebhookFunctionUrlConfig' 
